### ISSUE TITLE
Problema con Lombardia e Emilia Romagna

### ISSUE THREAD

**Issue by Spazio2001** [InPhyT/COVID19-Italy-Integrated-Surveillance-Data#1]
In output mancano i casi confermati divisi per genere di Lombardia e Emilia Romagna.

**Comment by pitmonticone** [comment]
### Italiano
La ringrazio per l'interesse @Spazio2001, le motivazioni che sottendono la mancanza provvisoria di quei dati di output sono già riportate alla sotto-sezione metodologica [Limitazioni](https://github.com/InPhyT/COVID19-Italy-Integrated-Surveillance-Data/blob/main/README-ITA.md#limitazioni).

### English 
Thank you for your interest @Spazio2001, the reasons behind the provisional absence of those output data are already reported in the methodological sub-section [Issues](https://github.com/InPhyT/COVID19-Italy-Integrated-Surveillance-Data/blob/main/README.md#issues).
